name: Update alphavantage fundamentals datasets

on:
  workflow_dispatch:
  schedule:
    - cron:  '5 11 * * *'

jobs:
      
  update_income_statement:
    runs-on: ubuntu-latest
    container: 
      image: riazarbi/datasci-quant:focal
      options: --user root
    env:
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_URL: ${{ secrets.S3_URL }}
      ALPHAVANTAGE: ${{ secrets.ALPHAVANTAGE }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Update alphavantage income statement dataset
      run: |-
        Rscript alphavantage_income_statement.R

  update_balance_sheet:
    runs-on: ubuntu-latest
    container: 
      image: riazarbi/datasci-quant:focal
      options: --user root
    env:
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_URL: ${{ secrets.S3_URL }}
      ALPHAVANTAGE: ${{ secrets.ALPHAVANTAGE }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Update alphavantage balance sheet dataset
      run: |-
        Rscript alphavantage_balance_sheet.R
        
  update_cash_flow:
    runs-on: ubuntu-latest
    container: 
      image: riazarbi/datasci-quant:focal
      options: --user root
    env:
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_URL: ${{ secrets.S3_URL }}
      ALPHAVANTAGE: ${{ secrets.ALPHAVANTAGE }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Update alphavantage cash flow dataset
      run: |-
        Rscript alphavantage_cash_flow.R
        
  update_earnings:
    runs-on: ubuntu-latest
    container: 
      image: riazarbi/datasci-quant:focal
      options: --user root
    env:
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_URL: ${{ secrets.S3_URL }}
      ALPHAVANTAGE: ${{ secrets.ALPHAVANTAGE }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Update alphavantage earnings dataset
      run: |-
        Rscript alphavantage_earnings.R
        