name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '36 */6 * * *'

jobs:
  scrape_wikipedia_sp500:
    runs-on: riazarbi/datasci-quant:focal
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://en.wikipedia.org/api/rest_v1/page/html/List_of_S%26P_500_companies  > data/wikipedia/sp500.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest wikipedia SP500 data: ${timestamp}" || exit 0
        git push
  scrape_tidyquant_sp500:
    runs-on: riazarbi/datasci-quant:focal
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        Rscript -e 'print("hello")'
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest tidyquant SP500 data: ${timestamp}" || exit 0
        git push
