name: Scrape S&P 500 constituents

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  scrape_wikipedia_sp500:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch wikipedia page
      run: |-
        mkdir -p data/wikipedia &&
        curl https://en.wikipedia.org/api/rest_v1/page/html/List_of_S%26P_500_companies  > data/wikipedia/sp500.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git pull
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest wikipedia SP500 constituent data: ${timestamp}" || exit 0
        git push
      
  scrape_tidyquant:
    runs-on: ubuntu-latest
    container: 
      image: riazarbi/datasci-quant:focal
      options: --user root
    env:
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_URL: ${{ secrets.S3_URL }}
      ALPHAVANTAGE: ${{ secrets.ALPHAVANTAGE }}
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Refresh sp500 constituent list
      run: |-
        Rscript SP500.R
